version: '3.8'
services:
  book-service:
    build:
      context: ./book-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    networks:
      - my-network

  author-service:
    build:
      context: ./author-service
    ports:
      - "3002:3001"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    networks:
      - my-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: library_management_service
    ports:
      - "5432:5432"
    networks:
      - my-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
